-- 코드를 입력하세요
SELECT 
    a.AUTHOR_ID,
    a.AUTHOR_NAME, 
    b.CATEGORY, 
    SUM(bs.SALES * b.PRICE) as TOTAL_SALES
FROM BOOK as b
JOIN AUTHOR as a ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES as bs ON b.BOOK_ID = bs.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC