-- 코드를 입력하세요
SELECT a.APNT_NO, p.PT_NAME, a.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT as a
INNER JOIN PATIENT as p on a.PT_NO = p.PT_NO
INNER JOIN DOCTOR as d on a.MDDR_ID = d.DR_ID
WHERE DATE(APNT_YMD) = '2022-04-13' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD 