-- 코드를 입력하세요
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE m
JOIN REST_REVIEW r ON m.MEMBER_ID = r.MEMBER_ID
WHERE m.MEMBER_ID = (   
    SELECT rr.MEMBER_ID 
    FROM REST_REVIEW rr
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC 
    LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT
    