-- 코드를 작성해주세요
SELECT SUM(SCORE) as SCORE,
hg.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL
FROM HR_GRADE as hg
INNER JOIN HR_EMPLOYEES as he ON hg.EMP_NO = he.EMP_NO
GROUP BY hg.EMP_NO
ORDER BY SCORE desc
LIMIT 1