-- 코드를 작성해주세요
SELECT hrd.DEPT_ID, hrd.DEPT_NAME_EN, ROUND(AVG(SAL)) as AVG_SAL
FROM HR_EMPLOYEES as hre
LEFT JOIN HR_DEPARTMENT as hrd ON hre.DEPT_ID = hrd.DEPT_ID
GROUP BY DEPT_ID, DEPT_NAME_EN
ORDER BY AVG_SAL DESC
